version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
#  console:
#    class: logging.StreamHandler
#    level: DEBUG
#    formatter: simple
#    stream: ext://sys.stdout
   file_handler:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: info.log
      mode: w

root:
  level: DEBUG
  handlers: [file_handler]
